stages:
  - build
  - deploy

variables:
  REACT_APP_ENV: "production"

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:18
  script:
    - npm install --force
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
  script:
    - scp -r build/* $SSH_USER@$SSH_HOST:$REMOTE_PATH
